package com.db.utils;

public class Constants {

	private Constants() {
	}

	public static final String SUCCESS = "success";
	public static final String FAUILER = "failure";
	public static final String HEADER = "Booking Confirmation on DIGITAL BIHAR, Bus: 22914, 25-Dec-2018, 3A, PNBE - UDN";
	public static final String OTP_HEADER = "Your OTP for new device sign-in";
	public static final String OTP_BODY = "<html><body><p> Dear <a href=\"#\" target=\"_blank\">USER_NAME</a>,<br> <br> We detected that you are trying to sign-in into a new browser. Your <b>OTP</b> for logging in is : <b>OTP_VALUES</b><br>For security reasons, please do not share this OTP with anyone.<br><br>Thank you,<br>Team Digital Bihar</p></body></html>";
	
	public static final String HTML_CONTENT = "<table width=\"100%\">\r\n" + "	<tbody>\r\n" + "		<tr>\r\n"
			+ "			<td colspan=\"2\"\r\n"
			+ "				style=\"font: 12px arial; color: #333; text-align: justify\"><hr>\r\n"
			+ "				<br> <b>This is a system generated mail. Please do not\r\n"
			+ "					reply to this email ID. If you have a query or need any\r\n"
			+ "					clarification you may: <br>(1) Call our 24-hour Customer Care\r\n"
			+ "					or<br>(2) Email Us <a href=\"mailto:care@irctc.co.in\"\r\n"
			+ "					target=\"_blank\">care@irctc.co.in</a>\r\n" + "			</b> <br>\r\n"
			+ "				<hr> <br></td>\r\n" + "		</tr>\r\n" + "		<tr>\r\n"
			+ "			<td style=\"border-bottom: 1px solid #ccc; font: 12px arial\"><div\r\n"
			+ "					style=\"font: bold 14px arial; color: #0099ff; margin: 0; padding: 0\">\r\n"
			+ "					<span>Ticket Confirmation</span>\r\n" + "				</div></td>\r\n"
			+ "			<td\r\n"
			+ "				style=\"font: bold 14px arial; color: #0099ff; border-bottom: 1px solid #ccc\"><img\r\n"
			+ "				alt=\"IRCTC\" style=\"float: right\"></td>\r\n" + "		</tr>\r\n" + "	</tbody>\r\n"
			+ "</table>\r\n" + "<br>\r\n" + "<p>\r\n" + "	<b>Dear satyam kumar,</b>\r\n" + "</p>\r\n"
			+ "<p style=\"text-align: justify; color: #000000; text-align: justify\">Congratulations!\r\n"
			+ "	Thank you for using IRCTCs online rail reservation facility. Your\r\n"
			+ "	e-ticket has been booked through IRCTC User Id: satyamk328 and the\r\n"
			+ "	details are indicated below.</p>\r\n"
			+ "<p style=\"text-align: justify; color: #000000\">Please take a\r\n"
			+ "	screenshot of ERS i.e. Virtual Reservation Message(VRM) OF YOUR TICKET\r\n"
			+ "	FROM YOUR Booked Tickets History page .You have to carry this VRM or\r\n"
			+ "	SMS send to you along with any one from the listed identity cards\r\n"
			+ "	(Voter Identity Card / Passport / PAN Card / Driving License / Photo ID\r\n"
			+ "	card issued by Central / State Govt / Public Sector Undertakings of\r\n"
			+ "	State / Central Government,District Administrations, Municipal bodies\r\n"
			+ "	and Panchayat Administrations which are having serial number/ Student\r\n"
			+ "	Identity Card with photograph issued by recognized School or College\r\n"
			+ "	for their students / Nationalised Bank Passbook with photograph /\r\n"
			+ "	Credit Cards issued by Banks with laminated photograph/ Unique\r\n"
			+ "	Identification Card \"Aadhaar\", m-Aadhaar, e-Aadhaar. / Passenger\r\n"
			+ "	showing the Aadhaar/Driving Licence from the “Issued Document” section\r\n"
			+ "	by logging into his/her DigiLocker account considered as valid proof of\r\n"
			+ "	identity (Documents uploaded by the user i.e. the document in “Uploaded\r\n"
			+ "	Document” section will not be considered as a valid proof of\r\n"
			+ "	identity).) during train journey in original. Both these i.e SMS or VRM\r\n"
			+ "	&amp; original ID will be examined by ticket checking staff on\r\n"
			+ "	stations/trains for verification purpose.</p>\r\n" + "<br>\r\n" + "<div\r\n"
			+ "	style=\"font: bold 14px arial; color: #0099ff; margin: 0; padding: 0\">\r\n"
			+ "	<span>Ticket Details</span>\r\n" + "</div>\r\n" + "<hr>\r\n"
			+ "<table width=\"100%\" cellpadding=\"5\">\r\n" + "	<tbody>\r\n" + "		<tr>\r\n"
			+ "			<td style=\"border-bottom: 1px solid #ccc; font: 12px arial\"><b>Transaction\r\n"
			+ "					ID : </b></td>\r\n"
			+ "			<td style=\"border-bottom: 1px solid #ccc; font: 12px arial\"><span>100001593674817</span></td>\r\n"
			+ "			<td style=\"border-bottom: 1px solid #ccc; font: 12px arial\"><b>PNR\r\n"
			+ "					No. :</b></td>\r\n"
			+ "			<td style=\"border-bottom: 1px solid #ccc; font: 12px arial\"><span>6323515196</span></td>\r\n"
			+ "			<td style=\"border-bottom: 1px solid #ccc; font: 12px arial\"><b>Train\r\n"
			+ "					No. / Name : </b></td>\r\n"
			+ "			<td style=\"border-bottom: 1px solid #ccc; font: 12px arial\"><span>22914\r\n"
			+ "					/ BDTS HUMSAFAR</span></td>\r\n" + "		</tr>\r\n" + "		<tr>\r\n"
			+ "			<td style=\"border-bottom: 1px solid #ccc; font: 12px arial\"><b>Date\r\n"
			+ "					of Booking : </b></td>\r\n"
			+ "			<td style=\"border-bottom: 1px solid #ccc; font: 12px arial\"><span>23-Dec-2018</span></td>\r\n"
			+ "			<td style=\"border-bottom: 1px solid #ccc; font: 12px arial\"><b>Class\r\n"
			+ "					: </b></td>\r\n"
			+ "			<td style=\"border-bottom: 1px solid #ccc; font: 12px arial\"><span>THIRD\r\n"
			+ "					AC</span></td>\r\n"
			+ "			<td style=\"border-bottom: 1px solid #ccc; font: 12px arial\"><b>Quota\r\n"
			+ "					: </b></td>\r\n"
			+ "			<td style=\"border-bottom: 1px solid #ccc; font: 12px arial\"><span>GENERAL\r\n"
			+ "			</span></td>\r\n" + "		</tr>\r\n" + "		<tr>\r\n"
			+ "			<td style=\"border-bottom: 1px solid #ccc; font: 12px arial\"><b>Date\r\n"
			+ "					of Journey : </b></td>\r\n"
			+ "			<td style=\"border-bottom: 1px solid #ccc; font: 12px arial\"><span>25-Dec-2018</span></td>\r\n"
			+ "			<td style=\"border-bottom: 1px solid #ccc; font: 12px arial\"><b>From\r\n"
			+ "					: </b></td>\r\n"
			+ "			<td style=\"border-bottom: 1px solid #ccc; font: 12px arial\"><span>PNBE</span></td>\r\n"
			+ "			<td style=\"border-bottom: 1px solid #ccc; font: 12px arial\"><b>To\r\n"
			+ "					: </b></td>\r\n"
			+ "			<td style=\"border-bottom: 1px solid #ccc; font: 12px arial\"><span>UDN</span></td>\r\n"
			+ "		</tr>\r\n" + "		<tr>\r\n"
			+ "			<td style=\"border-bottom: 1px solid #ccc; font: 12px arial\"><b>Boarding\r\n"
			+ "					At : </b></td>\r\n"
			+ "			<td style=\"border-bottom: 1px solid #ccc; font: 12px arial\"><span>PNBE</span></td>\r\n"
			+ "			<td style=\"border-bottom: 1px solid #ccc; font: 12px arial\"><b>Date\r\n"
			+ "					Of Boarding : </b></td>\r\n"
			+ "			<td style=\"border-bottom: 1px solid #ccc; font: 12px arial\"><span>25-Dec-2018</span>\r\n"
			+ "			</td>\r\n"
			+ "			<td style=\"border-bottom: 1px solid #ccc; font: 12px arial\"><b>Reservation\r\n"
			+ "					Up to :</b></td>\r\n"
			+ "			<td style=\"border-bottom: 1px solid #ccc; font: 12px arial\"><span>UDN</span></td>\r\n"
			+ "		</tr>\r\n" + "		<tr>\r\n"
			+ "			<td style=\"border-bottom: 1px solid #ccc; font: 12px arial\"><b>Scheduled\r\n"
			+ "					Departure* : </b></td>\r\n"
			+ "			<td style=\"border-bottom: 1px solid #ccc; font: 12px arial\"><span>23:10\r\n"
			+ "					Hrs</span></td>\r\n"
			+ "			<td style=\"border-bottom: 1px solid #ccc; font: 12px arial\"><b></b>\r\n"
			+ "			</td>\r\n"
			+ "			<td style=\"border-bottom: 1px solid #ccc; font: 12px arial\"><span></span>\r\n"
			+ "			</td>\r\n"
			+ "			<td style=\"border-bottom: 1px solid #ccc; font: 12px arial\"><b></b>\r\n"
			+ "			</td>\r\n"
			+ "			<td style=\"border-bottom: 1px solid #ccc; font: 12px arial\"><span></span>\r\n"
			+ "			</td>\r\n" + "		</tr>\r\n" + "		<tr></tr>\r\n" + "	</tbody>\r\n" + "</table>\r\n"
			+ "<p style=\"text-align: justify; color: #000000\">New Time table will\r\n"
			+ "	be effective w.e.f 15.08.2018. Departure time printed is liable to\r\n"
			+ "	change. Please check correct Departure from Railway Station Enquiry,\r\n"
			+ "	Dial 139 or SMS Rail to 139.</p>\r\n" + "<br>\r\n" + "<div\r\n"
			+ "	style=\"font: bold 14px arial; color: #0099ff; margin: 0; padding: 0\">\r\n"
			+ "	<span>Passenger Details</span>\r\n" + "</div>\r\n" + "<hr>\r\n"
			+ "<table width=\"100%\" cellpadding=\"5\">\r\n" + "	<tbody>\r\n"
			+ "		<tr align=\"left\" style=\"background-color: #f0f3ff\">\r\n"
			+ "			<td style=\"font-size: 12px\"><b>Sl. No.</b></td>\r\n"
			+ "			<td style=\"font-size: 12px\"><b>Name</b></td>\r\n"
			+ "			<td style=\"font-size: 12px\"><b>Age</b></td>\r\n"
			+ "			<td style=\"font-size: 12px\"><b>Gender</b></td>\r\n"
			+ "			<td style=\"font-size: 12px\"><b>Status</b></td>\r\n"
			+ "			<td style=\"font-size: 12px\"><b>Coach</b></td>\r\n"
			+ "			<td style=\"font-size: 12px\"><b>Seat / Berth / WL No</b></td>\r\n" + "		</tr>\r\n"
			+ "		<tr>\r\n" + "			<td style=\"border-bottom: 1px solid #ccc; font: 12px arial\">1</td>\r\n"
			+ "			<td style=\"border-bottom: 1px solid #ccc; font: 12px arial\">SANJIT\r\n"
			+ "				KUMAR</td>\r\n"
			+ "			<td style=\"border-bottom: 1px solid #ccc; font: 12px arial\">30</td>\r\n"
			+ "			<td style=\"border-bottom: 1px solid #ccc; font: 12px arial\">Male</td>\r\n"
			+ "			<td style=\"border-bottom: 1px solid #ccc; font: 12px arial\">RAC</td>\r\n"
			+ "			<td style=\"border-bottom: 1px solid #ccc; font: 12px arial\">&nbsp;</td>\r\n"
			+ "			<td style=\"border-bottom: 1px solid #ccc; font: 12px arial\">51&nbsp;</td>\r\n"
			+ "		</tr>\r\n" + "		<tr>\r\n"
			+ "			<td style=\"border-bottom: 1px solid #ccc; font: 12px arial\">2</td>\r\n"
			+ "			<td style=\"border-bottom: 1px solid #ccc; font: 12px arial\">NITU\r\n"
			+ "				DEVI</td>\r\n"
			+ "			<td style=\"border-bottom: 1px solid #ccc; font: 12px arial\">28</td>\r\n"
			+ "			<td style=\"border-bottom: 1px solid #ccc; font: 12px arial\">Female</td>\r\n"
			+ "			<td style=\"border-bottom: 1px solid #ccc; font: 12px arial\">RAC</td>\r\n"
			+ "			<td style=\"border-bottom: 1px solid #ccc; font: 12px arial\">&nbsp;</td>\r\n"
			+ "			<td style=\"border-bottom: 1px solid #ccc; font: 12px arial\">52&nbsp;</td>\r\n"
			+ "		</tr>\r\n" + "	</tbody>\r\n" + "</table>\r\n" + "<br>\r\n" + "<div\r\n"
			+ "	style=\"font: bold 14px arial; color: #0099ff; margin: 0; padding: 0\">\r\n"
			+ "	<span>Fare Details</span>\r\n" + "</div>\r\n" + "<hr>\r\n"
			+ "<table width=\"100%\" cellpadding=\"5\">\r\n" + "	<tbody>\r\n" + "		<tr>\r\n"
			+ "			<td style=\"border-bottom: 1px solid #ccc; font: 12px arial\"><b>Distance\r\n"
			+ "					:</b></td>\r\n"
			+ "			<td style=\"border-bottom: 1px solid #ccc; font: 12px arial\">1597\r\n"
			+ "				KM</td>\r\n" + "		</tr>\r\n" + "		<tr>\r\n"
			+ "			<td style=\"border-bottom: 1px solid #ccc; font: 12px arial\"><b>Ticket\r\n"
			+ "					Fare :</b></td>\r\n"
			+ "			<td style=\"border-bottom: 1px solid #ccc; font: 12px arial\">Rs.\r\n"
			+ "				5740.00</td>\r\n" + "		</tr>\r\n" + "		<tr>\r\n"
			+ "			<td style=\"border-bottom: 1px solid #ccc; font: 12px arial\"><b>Service\r\n"
			+ "					Charge (Inclusive of GST) :</b></td>\r\n"
			+ "			<td style=\"border-bottom: 1px solid #ccc; font: 12px arial\">Rs.\r\n"
			+ "				0.00</td>\r\n" + "		</tr>\r\n" + "		<tr>\r\n"
			+ "			<td style=\"border-bottom: 1px solid #ccc; font: 12px arial\"><b>Total\r\n"
			+ "					Fare :</b></td>\r\n"
			+ "			<td style=\"font: 110% strong; border-bottom: 1px solid #ccc\">Rs.\r\n"
			+ "				5740.00 *</td>\r\n" + "		</tr>\r\n" + "		<tr>\r\n"
			+ "			<td style=\"border-bottom: 1px solid #ccc; font: 12px arial\"\r\n"
			+ "				colspan=\"2\"><b>* Payment Gateway charges as applicable.</b></td>\r\n" + "		</tr>\r\n"
			+ "	</tbody>\r\n" + "</table>\r\n" + "<br>\r\n" + "<hr>\r\n" + "<div>\r\n" + "	<table>\r\n"
			+ "		<tbody>\r\n" + "			<tr>\r\n" + "				<td\r\n"
			+ "					style=\"font: bold 14px arial; color: #0099ff; margin: 0; padding: 0\"\r\n"
			+ "					rowspan=\"2\" valign=\"top\"><b>IRCTC SBI Platinum credit\r\n"
			+ "						card: </b></td>\r\n"
			+ "				<td>Book Free Train tickets using Reward Points on <a\r\n"
			+ "					href=\"https://www.irctc.co.in\" target=\"_blank\"\r\n"
			+ "					data-saferedirecturl=\"https://www.google.com/url?q=https://www.irctc.co.in&amp;source=gmail&amp;ust=1545641954747000&amp;usg=AFQjCNEGm7KJiC_kWsTtQFlFbgbvn8sJSg\">www.irctc.co.in</a></td>\r\n"
			+ "				<td rowspan=\"2\" valign=\"middle\"><a\r\n"
			+ "					href=\"https://www.sbicard.com/en/eapply/campaign.page?path=personal/credit-cards/travel/irctc-sbi-platinum-card.dcr&amp;GEMID1=dis_irctc_txt_ticket_acq_SEP_sbicard_e-apply&amp;GEMID2=irctc\"\r\n"
			+ "					style=\"font: bold 16px arial; background-color: #3665c2; color: #ffffff; border-radius: 13px; padding: 14px 25px; text-align: center; text-decoration: none; display: inline-block\"\r\n"
			+ "					target=\"_blank\"\r\n"
			+ "					data-saferedirecturl=\"https://www.google.com/url?q=https://www.sbicard.com/en/eapply/campaign.page?path%3Dpersonal/credit-cards/travel/irctc-sbi-platinum-card.dcr%26GEMID1%3Ddis_irctc_txt_ticket_acq_SEP_sbicard_e-apply%26GEMID2%3Dirctc&amp;source=gmail&amp;ust=1545641954747000&amp;usg=AFQjCNHDFDsx3NVSz5-3Huw1jfC3sT9UJA\">Apply\r\n"
			+ "						Now</a></td>\r\n" + "			</tr>\r\n" + "			<tr>\r\n"
			+ "				<td>Enjoy zero payment gateway charge</td>\r\n" + "			</tr>\r\n"
			+ "		</tbody>\r\n" + "	</table>\r\n" + "</div>\r\n" + "<hr>\r\n"
			+ "<p style=\"text-align: justify; color: #000000\">\r\n"
			+ "	For cancellation of your ticket, please log in to your account, select\r\n"
			+ "	the PNR you wish to cancel and cancel your ticket online. Cancellation\r\n"
			+ "	of your e-Ticket is possible only on the website <a\r\n"
			+ "		href=\"http://www.irctc.co.in\" target=\"_blank\"\r\n"
			+ "		data-saferedirecturl=\"https://www.google.com/url?q=http://www.irctc.co.in&amp;source=gmail&amp;ust=1545641954747000&amp;usg=AFQjCNEF3RswQ1L7chg2b4seZPVNJ3tDEg\">www.irctc.co.in</a>,\r\n"
			+ "	and is NOT possible on PRS Counters.\r\n" + "</p>\r\n"
			+ "<p style=\"text-align: justify; color: #000000\">You can cancel any of\r\n"
			+ "	the passenger names from the list of passengers on this ticket without\r\n"
			+ "	affecting the ticket as a whole.</p>\r\n"
			+ "<p style=\"text-align: justify; color: #000000\">This ticket is booked\r\n"
			+ "	on a personal user ID and can not be sold by an agent. If bought from\r\n"
			+ "	an agent by any individual, it is at his/her own risk</p>\r\n"
			+ "<p style=\"text-align: justify; color: #000000\">CANCELLATION OF\r\n" + "	E-TICKETS</p>\r\n"
			+ "<p style=\"text-align: justify; color: #000000\">\r\n"
			+ "	(1) E-Ticket can be cancelled online till preparation of charts (which\r\n"
			+ "	is normally 4 to 6 hours before the scheduled departure of the train\r\n"
			+ "	from the originating stations. (For trains starting up to 12 noon the\r\n"
			+ "	chart preparation is usually done on the previous night)) OR 4 hours\r\n"
			+ "	before the scheduled departure of boarding the train in case of\r\n"
			+ "	confirmed ticket OR 30 minutes before the scheduled departure of\r\n"
			+ "	boarding the train in case of RAC/WL whichever is earlier. If by any\r\n"
			+ "	reason you are unable to cancel your ticket on the website till the\r\n"
			+ "	time of charting please mail to <a href=\"mailto:etickets@irctc.co.in\"\r\n"
			+ "		target=\"_blank\">etickets@irctc.co.in</a>. User can check their refund\r\n"
			+ "	status online by clicking \"Refund Status\" link after logging in. All\r\n"
			+ "	refund will be processed as per extent Railway Refund Rules. Please\r\n"
			+ "	refer refund rules <a\r\n"
			+ "		href=\"http://contents.irctc.co.in/en/IRRules.html\" target=\"_blank\"\r\n"
			+ "		data-saferedirecturl=\"https://www.google.com/url?q=http://contents.irctc.co.in/en/IRRules.html&amp;source=gmail&amp;ust=1545641954747000&amp;usg=AFQjCNHZzlxDSf9QHAl_kxrHkyoeJRwisg\">here</a>.\r\n"
			+ "</p>\r\n" + "<p style=\"text-align: justify; color: #000000\">\r\n"
			+ "	(2) After preparation of charts, the user shall have to file online TDR\r\n"
			+ "	for claiming refund. IRCTC forward the case to concerned Zonal Railway\r\n"
			+ "	on the basis of Customer request through EDR and Enhance coaching\r\n"
			+ "	refund system. The refund case will be decided by Railways. The TDR can\r\n"
			+ "	be filed by the same user who books the ticket. After receipt of the\r\n"
			+ "	refund amount from Railway, it shall be credited only in the same\r\n"
			+ "	account through which booking was made through opted payment gateway.\r\n"
			+ "	If by any reason you are unable to file TDR through website please mail\r\n"
			+ "	to <a href=\"mailto:etickets@irctc.co.in\" target=\"_blank\">etickets@irctc.co.in</a>.\r\n"
			+ "	User can check TDR/Refund status through TDR History. All refund will\r\n"
			+ "	be process as per extent Railway Refund Rules. Please refer refund\r\n"
			+ "	rules <a href=\"http://contents.irctc.co.in/en/IRRules.html\"\r\n" + "		target=\"_blank\"\r\n"
			+ "		data-saferedirecturl=\"https://www.google.com/url?q=http://contents.irctc.co.in/en/IRRules.html&amp;source=gmail&amp;ust=1545641954747000&amp;usg=AFQjCNHZzlxDSf9QHAl_kxrHkyoeJRwisg\">here</a>.\r\n"
			+ "</p>\r\n" + "<p style=\"text-align: justify; color: #000000\">(3) Any refund amount\r\n"
			+ "	will be credited only in the same account through booking was made by\r\n"
			+ "	user. Customer is advised not to close that account so that refund\r\n"
			+ "	amount will be credited back.</p>\r\n"
			+ "<p style=\"text-align: justify; color: #000000\">Now User can change\r\n"
			+ "	Boarding Station from IRCTC's website.To Change Boarding Station Please\r\n"
			+ "	log into IRCTC website then go to Book Ticket History Page then Select\r\n"
			+ "	the PNR and Choose New Boarding Station.</p>\r\n"
			+ "<p style=\"text-align: justify; color: #000000\">\r\n"
			+ "	To View the Guidelines for Changing Boarding Station Please Click <a\r\n"
			+ "		href=\"http://contents.irctc.co.in/en/boardingPointChange.html\"\r\n"
			+ "		target=\"_blank\"\r\n"
			+ "		data-saferedirecturl=\"https://www.google.com/url?q=http://contents.irctc.co.in/en/boardingPointChange.html&amp;source=gmail&amp;ust=1545641954747000&amp;usg=AFQjCNH2BwzDYV_4z8bA9xhZlpge28Rk3w\">\r\n"
			+ "		here </a>\r\n" + "</p>\r\n"
			+ "<p style=\"text-align: justify; color: #000000\">For CHANGE IN NAME\r\n"
			+ "	customer can now approach the nearest Railway Reservation Office with\r\n"
			+ "	Electronic Reservation Slip print out and photo identity proof\r\n"
			+ "	mentioned in the Electronic Reservation Slip at least 24 hours before\r\n"
			+ "	the scheduled departure of train as per existing Railway rules.</p>\r\n"
			+ "<p style=\"text-align: justify; color: #000000\">Once you have\r\n"
			+ "	cancelled your ticket, the fresh details and changes made by you will\r\n"
			+ "	be available on the Cancelled e-Tickets History (as a link to site).\r\n"
			+ "	The refund amount due to you after cancellation will be credited back\r\n"
			+ "	to the same account which you had used for booking the ticket.</p>\r\n"
			+ "<p style=\"text-align: justify; color: #000000\">\r\n"
			+ "	Passengers are advised not to carry inflammable/dangerous/\r\n" + "	<wbr>\r\n"
			+ "	explosive articles as part of their luggage and also to desist from\r\n"
			+ "	smoking in the trains.\r\n" + "</p>\r\n" + "<p style=\"text-align: justify; color: #000000\">\r\n"
			+ "	For any further assistance, please contact us at 24*7 Hrs.<br>Customer\r\n"
			+ "	Support at <b>0755-3934141, 0755-6610661</b> or mail us at <a\r\n"
			+ "		href=\"mailto:care@irctc.co.in\" target=\"_blank\">care@irctc.co.in</a>.\r\n" + "</p>\r\n"
			+ "<p style=\"color: #646464\">\r\n"
			+ "	<b>Just dial 139 from your landline, mobile &amp; CDMA phones for\r\n"
			+ "		railway enquiries.</b>\r\n" + "</p>\r\n" + "<p style=\"text-align: justify; color: #000000\">\r\n"
			+ "	To book and get food delivered on your train berth, please call IRCTC\r\n"
			+ "	Toll free No. 1323 or log in at <a\r\n"
			+ "		href=\"http://www.ecatering.irctc.co.in\" target=\"_blank\"\r\n"
			+ "		data-saferedirecturl=\"https://www.google.com/url?q=http://www.ecatering.irctc.co.in&amp;source=gmail&amp;ust=1545641954747000&amp;usg=AFQjCNGaMiElvbo5ClTMOkxEr-ymJL1qxw\">www.ecatering.irctc.co.in</a>\r\n"
			+ "</p>\r\n" + "<p style=\"color: #757575\">\r\n"
			+ "	<b>******************************<wbr>** Information\r\n"
			+ "		******************************<wbr>*******\r\n" + "	</b>\r\n" + "</p>\r\n"
			+ "<p style=\"text-align: justify; color: #757575\">For any enquiries or\r\n"
			+ "	information regarding your transaction with IRCTC, do not provide your\r\n"
			+ "	credit/debit card details by any means to IRCTC. All your queries can\r\n"
			+ "	be replied on the basis of 15 digit IRCTC Transaction id/ 10 digit PNR\r\n"
			+ "	no./ User id. IRCTC does not store the credit/ debit card information\r\n"
			+ "	in any form during the transaction.</p>\r\n" + "<p style=\"color: #757575\">\r\n"
			+ "	<b>******************************<wbr>******************************<wbr>**********************\r\n"
			+ "	</b>\r\n" + "</p>\r\n" + "<p style=\"color: #0099ff; font: bold 14px arial\">\r\n"
			+ "	<b>Please don't print unless extremely necessary.</b>\r\n" + "</p>\r\n" + "<br>\r\n" + "<br>\r\n"
			+ "<p>\r\n" + "	<b>Warm Regards,<br>Customer Care<br>Internet Ticketing<br>IRCTC\r\n" + "	</b>\r\n"
			+ "</p>\r\n" + "";

}
